### ISSUE TITLE
video content

### ISSUE THREAD

**Issue by gabeio** [HackKean/hackkean.github.io#4]
You'll want to keep large binary files (like videos and large images) out of the repo because git starts to really hurt computers when it gets too big (which is why they added [git lfs](https://git-lfs.github.com/) but [github does not serve the lfs files](https://github.com/github/git-lfs/issues/791) as it does the rest of the files *sigh*).

I copied the video to [divshot](https://firebase.google.com/pricing/) (which apparently is now on google's api and doesn't actually mention divshot itself 😞 ).

https://firebasestorage.googleapis.com/v0/b/hackkean-f36a8.appspot.com/o/kean.mp4?alt=media&token=ec20c4ff-5a06-486c-9e4c-c5baaf4a25e9

it's the pure video unlike a youtube upload (tried that first lol)...(they apparently break the video files into tons of little megabytes literally.)

I added your kean email as an owner of the app on firebase/divshot so you can add other videos as needed.

**Comment by jonmrod** [comment]
nice, i'll give this a try. closing issue

**Comment by gabeio** [comment]
btw you can mention issues (with links) and close the from commit messages https://help.github.com/articles/closing-issues-via-commit-messages for future reference 👍  I believe you can also do it accross repositories if you add the username/repo#issue...
